[package]
name = "Town-Map-Procedural-Generation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast_inv_sqrt = "1.0.1"
rand = "0.8"
macroquad = "0.3"